import { MARKER_UID } from './uidScheme.js';

const MARKER_COMMENT = '⚠ Managed by Weyland-Registrar (do not edit)';

/**
 * A disabled, non-injecting WI entry identifying a book as owned by this
 * extension -- the "commented-out header" this book carries going forward.
 * Every full rebuild (syncCharacterBook/syncLocationBook, via
 * writeAndActivate) includes this alongside its real entries.
 * @returns {object}
 */
export function buildMarkerEntry() {
    return {
        uid: MARKER_UID,
        key: [],
        keysecondary: [],
        comment: MARKER_COMMENT,
        content:
            'This lorebook is fully regenerated by the Weyland-Registrar extension every time its catalog syncs. ' +
            'Entries added or edited here by hand will be overwritten on the next sync. If this extension ever found ' +
            'pre-existing content under this same book name without this marker, it preserved that content in a ' +
            'separate backup book (visible in the World Info list) before taking over.',
        constant: false,
        disable: true,
        position: 0,
        order: -1,
    };
}

function hasMarker(entries) {
    return entries?.[MARKER_UID]?.comment === MARKER_COMMENT;
}

function formatBackupTimestamp() {
    const d = new Date();
    const pad = (n) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}-${pad(d.getMinutes())}-${pad(d.getSeconds())}`;
}

/**
 * Finds a backup name that isn't already in use, appending "#2", "#3", ...
 * if needed. Guards against two collisions landing in the same
 * second-resolution timestamp (e.g. two rapid retries) silently
 * overwriting an earlier backup instead of getting their own.
 * @param {object} stContext - needs loadWorldInfo
 * @param {string} baseName
 * @returns {Promise<string>}
 */
async function findFreeBackupName(stContext, baseName) {
    let candidate = baseName;
    for (let attempt = 2; ; attempt++) {
        const existing = await stContext.loadWorldInfo(candidate);
        if (Object.keys(existing?.entries ?? {}).length === 0) return candidate;
        candidate = `${baseName} #${attempt}`;
    }
}

/**
 * If a book of this name already has real content but wasn't written by
 * this extension (a coincidentally-named user lorebook, one predating this
 * marker, or one a user's manual edit stripped the marker from), preserves
 * it under a new backup name before this extension overwrites it. Safe to
 * call on every sync: once the marker is present the check is a no-op, so
 * no separate "have we already taken ownership" flag needs to be tracked in
 * settings -- the marker entry itself is that flag, self-describing
 * directly in the book. Does NOT activate the backup book -- it's a
 * preserved artifact, not something that should start injecting into
 * prompts.
 * @param {object} stContext - needs loadWorldInfo, saveWorldInfo
 * @param {string} bookName
 * @returns {Promise<string|null>} the backup book's name if one was made, else null
 */
export async function ensureBookOwnership(stContext, bookName) {
    const existing = await stContext.loadWorldInfo(bookName);
    const existingEntries = existing?.entries ?? {};
    if (Object.keys(existingEntries).length === 0) return null;
    if (hasMarker(existingEntries)) return null;

    const backupName = await findFreeBackupName(stContext, `${bookName} (Backup ${formatBackupTimestamp()})`);
    await stContext.saveWorldInfo(backupName, existing, true);
    return backupName;
}
